export const test = [
  {
    id: 103851,
    title: "5-toubun no Hanayome",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/manga/2/201572.jpg",
      large: "https://api-cdn.myanimelist.net/images/manga/2/201572l.jpg",
    },
    alternative_titles: {
      synonyms: ["Gotoubun no Hanayome", "The Five Wedded Brides"],
      en: "The Quintessential Quintuplets",
      ja: "五等分の花嫁",
    },
    start_date: "2017-08-09",
    end_date: "2020-02-19",
    mean: 7.97,
    rank: 752,
    genres: [
      {
        id: 22,
        name: "Romance",
      },
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 35,
        name: "Harem",
      },
      {
        id: 23,
        name: "School",
      },
      {
        id: 27,
        name: "Shounen",
      },
    ],
    media_type: "manga",
    my_list_status: {
      status: "completed",
      is_rereading: false,
      num_volumes_read: 14,
      num_chapters_read: 122,
      score: 9,
      updated_at: "2020-02-24T23:32:56+00:00",
      start_date: "2019-03-29",
      finish_date: "2020-02-23",
    },
    num_volumes: 14,
    num_chapters: 122,
    image_url_id: "2/201572",
    title_en: "The Quintessential Quintuplets",
    title_ja: "五等分の花嫁",
  },
  {
    id: 42451,
    title: "Horimiya",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/manga/2/245008.jpg",
      large: "https://api-cdn.myanimelist.net/images/manga/2/245008l.jpg",
    },
    alternative_titles: {
      synonyms: [],
      en: "Horimiya",
      ja: "ホリミヤ",
    },
    start_date: "2011-10-18",
    end_date: "2021-03-18",
    mean: 8.46,
    rank: 138,
    genres: [
      {
        id: 22,
        name: "Romance",
      },
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 23,
        name: "School",
      },
      {
        id: 36,
        name: "Slice of Life",
      },
      {
        id: 27,
        name: "Shounen",
      },
    ],
    media_type: "manga",
    my_list_status: {
      status: "reading",
      is_rereading: false,
      num_volumes_read: 6,
      num_chapters_read: 45,
      score: 0,
      updated_at: "2019-03-29T12:41:19+00:00",
      start_date: "2019-02-23",
    },
    num_volumes: 16,
    num_chapters: 125,
    image_url_id: "2/245008",
    title_en: "Horimiya",
    title_ja: "ホリミヤ",
  },
  {
    id: 7519,
    title: "Kami nomi zo Shiru Sekai",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/manga/2/188974.jpg",
      large: "https://api-cdn.myanimelist.net/images/manga/2/188974l.jpg",
    },
    alternative_titles: {
      synonyms: [
        "KamiNomi",
        "Kami nomizo Shiru Sekai",
        "The World God Only Knows",
        "TWGOK",
      ],
      en: "",
      ja: "神のみぞ知るセカイ",
    },
    start_date: "2008-04-09",
    end_date: "2014-04-23",
    mean: 8.49,
    rank: 125,
    genres: [
      {
        id: 10,
        name: "Fantasy",
      },
      {
        id: 22,
        name: "Romance",
      },
      {
        id: 37,
        name: "Supernatural",
      },
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 35,
        name: "Harem",
      },
      {
        id: 23,
        name: "School",
      },
      {
        id: 27,
        name: "Shounen",
      },
    ],
    media_type: "manga",
    my_list_status: {
      status: "plan_to_read",
      is_rereading: false,
      num_volumes_read: 0,
      num_chapters_read: 0,
      score: 0,
      updated_at: "2019-03-15T19:07:36+00:00",
    },
    num_volumes: 26,
    num_chapters: 271,
    image_url_id: "2/188974",
    title_en: "Kami nomi zo Shiru Sekai",
    title_ja: "神のみぞ知るセカイ",
  },
  {
    id: 48035,
    title: "Wagatsuma-san wa Ore no Yome",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/manga/2/164478.jpg",
      large: "https://api-cdn.myanimelist.net/images/manga/2/164478l.jpg",
    },
    alternative_titles: {
      synonyms: [],
      en: "My Wife Is Wagatsuma-san",
      ja: "我妻さんは俺のヨメ",
    },
    start_date: "2011-09-20",
    end_date: "2014-09-24",
    mean: 7.38,
    rank: 3495,
    genres: [
      {
        id: 22,
        name: "Romance",
      },
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 23,
        name: "School",
      },
      {
        id: 36,
        name: "Slice of Life",
      },
      {
        id: 27,
        name: "Shounen",
      },
    ],
    media_type: "manga",
    my_list_status: {
      status: "completed",
      is_rereading: false,
      num_volumes_read: 13,
      num_chapters_read: 111,
      score: 8,
      updated_at: "2019-08-31T17:26:47+00:00",
      start_date: "2019-08-28",
      finish_date: "2019-08-31",
    },
    num_volumes: 13,
    num_chapters: 111,
    image_url_id: "2/164478",
    title_en: "My Wife Is Wagatsuma-san",
    title_ja: "我妻さんは俺のヨメ",
  },
  {
    id: 62547,
    title: "Yugami-kun ni wa Tomodachi ga Inai",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/manga/1/107515.jpg",
      large: "https://api-cdn.myanimelist.net/images/manga/1/107515l.jpg",
    },
    alternative_titles: {
      synonyms: [],
      en: "He does not have any friends.",
      ja: "湯神くんには友達がいない",
    },
    start_date: "2012-05-25",
    end_date: "2019-05-22",
    mean: 8.22,
    rank: 359,
    genres: [
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 23,
        name: "School",
      },
      {
        id: 27,
        name: "Shounen",
      },
      {
        id: 36,
        name: "Slice of Life",
      },
    ],
    media_type: "manga",
    my_list_status: {
      status: "reading",
      is_rereading: false,
      num_volumes_read: 1,
      num_chapters_read: 8,
      score: 0,
      updated_at: "2019-09-18T19:59:08+00:00",
      start_date: "2019-09-11",
    },
    num_volumes: 16,
    num_chapters: 81,
    image_url_id: "1/107515",
    title_en: "He does not have any friends.",
    title_ja: "湯神くんには友達がいない",
  },
];
