export const animes = [
  {
    id: 37786,
    title: "Yagate Kimi ni Naru",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/1783/96153.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/1783/96153l.jpg",
    },
    alternative_titles: {
      synonyms: ["YagaKimi", "Eventually, I Will Become You"],
      en: "Bloom Into You",
      ja: "やがて君になる",
    },
    start_date: "2018-10-05",
    end_date: "2018-12-28",
    mean: 7.92,
    genres: [
      { id: 8, name: "Drama" },
      { id: 22, name: "Romance" },
      { id: 23, name: "School" },
      { id: 26, name: "Shoujo Ai" },
    ],
    media_type: "tv",
    status: "finished_airing",
    my_list_status: {
      status: "plan_to_watch",
      score: 0,
      num_episodes_watched: 0,
      is_rewatching: false,
      updated_at: "2019-09-29T04:36:35+00:00",
      num_times_rewatched: 0,
    },
    num_episodes: 13,
    start_season: { year: 2018, season: "fall" },
    broadcast: { day_of_the_week: "friday", start_time: "21:30" },
    source: "manga",
    average_episode_duration: 1465,
    studios: [{ id: 1103, name: "TROYCA" }],
    image_url_id: "1783/96153",
    time_watched: 0,
    title_en: "Bloom Into You",
    title_ja: "やがて君になる",
  },
  {
    id: 6862,
    title: "K-On!: Live House!",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/9/15892.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/9/15892l.jpg",
    },
    alternative_titles: {
      synonyms: ["K-On! OVA", "Keion OVA", "K-On! Episode 14", "Keion OVA"],
      en: "",
      ja: "けいおん! ライブハウス!",
    },
    start_date: "2010-01-19",
    end_date: "2010-01-19",
    mean: 7.83,
    genres: [
      { id: 4, name: "Comedy" },
      { id: 19, name: "Music" },
      { id: 23, name: "School" },
      { id: 36, name: "Slice of Life" },
    ],
    media_type: "special",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 0,
      num_episodes_watched: 1,
      is_rewatching: false,
      updated_at: "2019-08-11T06:23:27+00:00",
      num_times_rewatched: 1,
    },
    num_episodes: 1,
    start_season: { year: 2010, season: "winter" },
    source: "4_koma_manga",
    average_episode_duration: 1421,
    studios: [{ id: 2, name: "Kyoto Animation" }],
    image_url_id: "9/15892",
    time_watched: 2842,
    title_en: "K-On!: Live House!",
    title_ja: "けいおん! ライブハウス!",
  },
  {
    id: 14811,
    title: "GJ-bu",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/10/45995.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/10/45995l.jpg",
    },
    alternative_titles: {
      synonyms: ["Good Job-bu"],
      en: "GJ Club",
      ja: "GJ部",
    },
    start_date: "2013-01-10",
    end_date: "2013-03-28",
    mean: 7.33,
    genres: [
      { id: 4, name: "Comedy" },
      { id: 23, name: "School" },
      { id: 36, name: "Slice of Life" },
    ],
    media_type: "tv",
    status: "finished_airing",
    my_list_status: {
      status: "plan_to_watch",
      score: 0,
      num_episodes_watched: 0,
      is_rewatching: false,
      updated_at: "2019-05-15T17:43:53+00:00",
      num_times_rewatched: 0,
    },
    num_episodes: 12,
    start_season: { year: 2013, season: "winter" },
    source: "light_novel",
    average_episode_duration: 1380,
    studios: [{ id: 95, name: "Doga Kobo" }],
    image_url_id: "10/45995",
    time_watched: 0,
    title_en: "GJ Club",
    title_ja: "GJ部",
  },
  {
    id: 10521,
    title: "Working'!!",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/3/75263.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/3/75263l.jpg",
    },
    alternative_titles: {
      synonyms: ["Working!! 2"],
      en: "Wagnaria!!2",
      ja: "ワーキング’！！",
    },
    start_date: "2011-10-01",
    end_date: "2011-12-24",
    mean: 7.85,
    genres: [
      { id: 4, name: "Comedy" },
      { id: 22, name: "Romance" },
      { id: 42, name: "Seinen" },
      { id: 36, name: "Slice of Life" },
    ],
    media_type: "tv",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 8,
      num_episodes_watched: 13,
      is_rewatching: false,
      updated_at: "2019-05-27T02:48:01+00:00",
      start_date: "2019-05-24",
      finish_date: "2019-05-26",
      num_times_rewatched: 0,
    },
    num_episodes: 13,
    start_season: { year: 2011, season: "fall" },
    source: "4_koma_manga",
    average_episode_duration: 1440,
    studios: [{ id: 56, name: "A-1 Pictures" }],
    image_url_id: "3/75263",
    time_watched: 18720,
    title_en: "Wagnaria!!2",
    title_ja: "ワーキング’！！",
  },
];
