export const animes = [
  {
    id: 6547,
    title: "Angel Beats!",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/1244/111115.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/1244/111115l.jpg",
    },
    alternative_titles: {
      synonyms: [],
      en: "Angel Beats!",
      ja: "Angel Beats!（エンジェルビーツ）",
    },
    start_date: "2010-04-03",
    end_date: "2010-06-26",
    mean: 8.11,
    genres: [
      {
        id: 1,
        name: "Action",
      },
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 8,
        name: "Drama",
      },
      {
        id: 23,
        name: "School",
      },
      {
        id: 37,
        name: "Supernatural",
      },
    ],
    media_type: "tv",
    status: "finished_airing",
    my_list_status: {
      status: "plan_to_watch",
      score: 0,
      num_episodes_watched: 0,
      is_rewatching: false,
      updated_at: "2019-06-27T23:04:27+00:00",
      num_times_rewatched: 0,
    },
    num_episodes: 13,
    start_season: {
      year: 2010,
      season: "spring",
    },
    source: "original",
    average_episode_duration: 1470,
    studios: [
      {
        id: 132,
        name: "P.A. Works",
      },
    ],
    image_url_id: "1244/111115",
    time_watched: 0,
    title_en: "Angel Beats!",
    title_ja: "Angel Beats!（エンジェルビーツ）",
  },
  {
    id: 37497,
    title: "Irozuku Sekai no Ashita kara",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/1424/93855.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/1424/93855l.jpg",
    },
    alternative_titles: {
      synonyms: [],
      en: "Iroduku: The World in Colors",
      ja: "色づく世界の明日から",
    },
    start_date: "2018-10-06",
    end_date: "2018-12-29",
    mean: 7.53,
    genres: [
      {
        id: 8,
        name: "Drama",
      },
      {
        id: 16,
        name: "Magic",
      },
      {
        id: 22,
        name: "Romance",
      },
      {
        id: 23,
        name: "School",
      },
    ],
    media_type: "tv",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 7,
      num_episodes_watched: 13,
      is_rewatching: false,
      updated_at: "2018-12-31T05:00:04+00:00",
      start_date: "2018-10-14",
      finish_date: "2018-12-30",
      num_times_rewatched: 0,
    },
    num_episodes: 13,
    start_season: {
      year: 2018,
      season: "fall",
    },
    broadcast: {
      day_of_the_week: "saturday",
      start_time: "01:55",
    },
    source: "original",
    average_episode_duration: 1453,
    studios: [
      {
        id: 132,
        name: "P.A. Works",
      },
    ],
    image_url_id: "1424/93855",
    time_watched: 18889,
    title_en: "Iroduku: The World in Colors",
    title_ja: "色づく世界の明日から",
  },
  {
    id: 38759,
    title: "Sewayaki Kitsune no Senko-san",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/1814/99677.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/1814/99677l.jpg",
    },
    alternative_titles: {
      synonyms: ["Meddlesome Kitsune Senko-san"],
      en: "The Helpful Fox Senko-san",
      ja: "世話やきキツネの仙狐さん",
    },
    start_date: "2019-04-10",
    end_date: "2019-06-26",
    mean: 7.35,
    genres: [
      {
        id: 36,
        name: "Slice of Life",
      },
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 37,
        name: "Supernatural",
      },
      {
        id: 22,
        name: "Romance",
      },
    ],
    media_type: "tv",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 7,
      num_episodes_watched: 12,
      is_rewatching: false,
      updated_at: "2019-06-27T19:38:22+00:00",
      start_date: "2019-04-10",
      finish_date: "2019-06-27",
      num_times_rewatched: 0,
    },
    num_episodes: 12,
    start_season: {
      year: 2019,
      season: "spring",
    },
    broadcast: {
      day_of_the_week: "wednesday",
      start_time: "22:30",
    },
    source: "web_manga",
    average_episode_duration: 1425,
    studios: [
      {
        id: 95,
        name: "Doga Kobo",
      },
    ],
    image_url_id: "1814/99677",
    time_watched: 17100,
    title_en: "The Helpful Fox Senko-san",
    title_ja: "世話やきキツネの仙狐さん",
  },
  {
    id: 39808,
    title: "Non Non Biyori Nonstop",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/1033/111540.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/1033/111540l.jpg",
    },
    alternative_titles: {
      synonyms: ["Non Non Biyori 3rd Season", "Non Non Biyori Third Season"],
      en: "Non Non Biyori Nonstop",
      ja: "のんのんびより のんすとっぷ",
    },
    start_date: "2021-01-11",
    end_date: "2021-03-29",
    mean: 8.41,
    genres: [
      {
        id: 36,
        name: "Slice of Life",
      },
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 42,
        name: "Seinen",
      },
    ],
    media_type: "tv",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 9,
      num_episodes_watched: 12,
      is_rewatching: false,
      updated_at: "2021-04-19T06:05:18+00:00",
      start_date: "2021-04-05",
      finish_date: "2021-04-19",
      num_times_rewatched: 0,
    },
    num_episodes: 12,
    start_season: {
      year: 2021,
      season: "winter",
    },
    broadcast: {
      day_of_the_week: "monday",
      start_time: "01:35",
    },
    source: "manga",
    average_episode_duration: 1494,
    studios: [
      {
        id: 300,
        name: "SILVER LINK.",
      },
    ],
    image_url_id: "1033/111540",
    time_watched: 17928,
    title_en: "Non Non Biyori Nonstop",
    title_ja: "のんのんびより のんすとっぷ",
  },
  {
    id: 25781,
    title: "Shingeki no Kyojin: Kuinaki Sentaku",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/8/69497.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/8/69497l.jpg",
    },
    alternative_titles: {
      synonyms: [
        "Attack on Titan: No Regrets",
        "Shingeki no Kyojin: Birth of Levi",
      ],
      en: "",
      ja: "進撃の巨人 悔いなき選択",
    },
    start_date: "2014-12-09",
    end_date: "2015-04-09",
    mean: 8.41,
    genres: [
      {
        id: 1,
        name: "Action",
      },
      {
        id: 10,
        name: "Fantasy",
      },
      {
        id: 25,
        name: "Shoujo",
      },
    ],
    media_type: "ova",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 0,
      num_episodes_watched: 2,
      is_rewatching: false,
      updated_at: "2020-06-10T04:52:02+00:00",
      start_date: "2020-06-09",
      finish_date: "2020-06-09",
      num_times_rewatched: 0,
    },
    num_episodes: 2,
    start_season: {
      year: 2014,
      season: "fall",
    },
    source: "visual_novel",
    average_episode_duration: 1620,
    studios: [
      {
        id: 858,
        name: "Wit Studio",
      },
    ],
    image_url_id: "8/69497",
    time_watched: 3240,
    title_en: "Shingeki no Kyojin: Kuinaki Sentaku",
    title_ja: "進撃の巨人 悔いなき選択",
  },
  {
    id: 36098,
    title: "Kimi no Suizou wo Tabetai",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/1768/93291.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/1768/93291l.jpg",
    },
    alternative_titles: {
      synonyms: ["KimiSui", "Let Me Eat Your Pancreas"],
      en: "I want to eat your pancreas",
      ja: "君の膵臓をたべたい",
    },
    start_date: "2018-09-01",
    end_date: "2018-09-01",
    mean: 8.59,
    genres: [
      {
        id: 36,
        name: "Slice of Life",
      },
      {
        id: 8,
        name: "Drama",
      },
      {
        id: 22,
        name: "Romance",
      },
    ],
    media_type: "movie",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 9,
      num_episodes_watched: 1,
      is_rewatching: false,
      updated_at: "2019-05-19T06:17:40+00:00",
      num_times_rewatched: 0,
    },
    num_episodes: 1,
    start_season: {
      year: 2018,
      season: "summer",
    },
    source: "novel",
    average_episode_duration: 6522,
    studios: [
      {
        id: 1244,
        name: "Studio VOLN",
      },
    ],
    image_url_id: "1768/93291",
    time_watched: 6522,
    title_en: "I want to eat your pancreas",
    title_ja: "君の膵臓をたべたい",
  },
  {
    id: 38414,
    title: "Re:Zero kara Hajimeru Isekai Seikatsu - Hyouketsu no Kizuna",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/1238/104023.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/1238/104023l.jpg",
    },
    alternative_titles: {
      synonyms: ["Re:Zero kara Hajimeru Isekai Seikatsu OVA 2"],
      en: "Re:ZERO -Starting Life in Another World- The Frozen Bond",
      ja: "Re：ゼロから始める異世界生活『氷結の絆』",
    },
    start_date: "2019-11-08",
    end_date: "2019-11-08",
    mean: 7.6,
    genres: [
      {
        id: 40,
        name: "Psychological",
      },
      {
        id: 8,
        name: "Drama",
      },
      {
        id: 41,
        name: "Thriller",
      },
      {
        id: 10,
        name: "Fantasy",
      },
    ],
    media_type: "movie",
    status: "finished_airing",
    my_list_status: {
      status: "plan_to_watch",
      score: 0,
      num_episodes_watched: 0,
      is_rewatching: false,
      updated_at: "2020-07-10T01:29:51+00:00",
      num_times_rewatched: 0,
    },
    num_episodes: 1,
    start_season: {
      year: 2019,
      season: "fall",
    },
    source: "light_novel",
    average_episode_duration: 4571,
    studios: [
      {
        id: 314,
        name: "White Fox",
      },
    ],
    image_url_id: "1238/104023",
    time_watched: 0,
    title_en: "Re:ZERO -Starting Life in Another World- The Frozen Bond",
    title_ja: "Re：ゼロから始める異世界生活『氷結の絆』",
  },
  {
    id: 34855,
    title: "Gabriel DropOut Specials",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/8/89690.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/8/89690l.jpg",
    },
    alternative_titles: {
      synonyms: [],
      en: "",
      ja: "ガヴリールドロップアウトOVA",
    },
    start_date: "2017-03-24",
    end_date: "2017-05-24",
    mean: 7.64,
    genres: [
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 6,
        name: "Demons",
      },
      {
        id: 37,
        name: "Supernatural",
      },
      {
        id: 23,
        name: "School",
      },
      {
        id: 27,
        name: "Shounen",
      },
    ],
    media_type: "special",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 0,
      num_episodes_watched: 2,
      is_rewatching: false,
      updated_at: "2020-01-09T07:34:11+00:00",
      start_date: "2020-01-09",
      finish_date: "2020-01-09",
      num_times_rewatched: 0,
    },
    num_episodes: 2,
    start_season: {
      year: 2017,
      season: "winter",
    },
    source: "manga",
    average_episode_duration: 936,
    studios: [
      {
        id: 95,
        name: "Doga Kobo",
      },
    ],
    image_url_id: "8/89690",
    time_watched: 1872,
    title_en: "Gabriel DropOut Specials",
    title_ja: "ガヴリールドロップアウトOVA",
  },
  {
    id: 35466,
    title: "ReLIFE: Kanketsu-hen",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/1566/91061.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/1566/91061l.jpg",
    },
    alternative_titles: {
      synonyms: ["ReLIFE Final Arc"],
      en: "",
      ja: "ReLIFE 完結編",
    },
    start_date: "2018-03-21",
    end_date: "2018-03-21",
    mean: 8.22,
    genres: [
      {
        id: 22,
        name: "Romance",
      },
      {
        id: 23,
        name: "School",
      },
      {
        id: 36,
        name: "Slice of Life",
      },
    ],
    media_type: "special",
    status: "finished_airing",
    my_list_status: {
      status: "completed",
      score: 7,
      num_episodes_watched: 4,
      is_rewatching: false,
      updated_at: "2018-08-02T17:15:21+00:00",
      num_times_rewatched: 0,
    },
    num_episodes: 4,
    start_season: {
      year: 2018,
      season: "winter",
    },
    source: "web_manga",
    average_episode_duration: 1420,
    studios: [
      {
        id: 73,
        name: "TMS Entertainment",
      },
    ],
    image_url_id: "1566/91061",
    time_watched: 5680,
    title_en: "ReLIFE: Kanketsu-hen",
    title_ja: "ReLIFE 完結編",
  },
  {
    id: 36038,
    title: "Net-juu no Susume",
    main_picture: {
      medium: "https://api-cdn.myanimelist.net/images/anime/3/87463.jpg",
      large: "https://api-cdn.myanimelist.net/images/anime/3/87463l.jpg",
    },
    alternative_titles: {
      synonyms: ["Netojuu no Susume"],
      en: "Recovery of an MMO Junkie",
      ja: "ネト充のススメ",
    },
    start_date: "2017-10-10",
    end_date: "2017-12-12",
    mean: 7.6,
    genres: [
      {
        id: 11,
        name: "Game",
      },
      {
        id: 4,
        name: "Comedy",
      },
      {
        id: 22,
        name: "Romance",
      },
    ],
    media_type: "ona",
    status: "finished_airing",
    my_list_status: {
      status: "plan_to_watch",
      score: 0,
      num_episodes_watched: 0,
      is_rewatching: false,
      updated_at: "2019-06-27T22:33:58+00:00",
      num_times_rewatched: 0,
    },
    num_episodes: 10,
    start_season: {
      year: 2017,
      season: "fall",
    },
    source: "web_manga",
    average_episode_duration: 1420,
    studios: [
      {
        id: 1278,
        name: "Signal.MD",
      },
    ],
    image_url_id: "3/87463",
    time_watched: 0,
    title_en: "Recovery of an MMO Junkie",
    title_ja: "ネト充のススメ",
  },
];
